default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "vd29263.ap-south-1.aws"
      user: "Chinmay"
      password: "sigmoidSnow@1"
      role: "SYSADMIN"
      database: "analytics"
      warehouse: "transforming"
      schema: ""
      threads: 25
      